### ISSUE TITLE
Open to elaboration of usage as a library

### ISSUE THREAD

**Issue by yoiang** [BlinkTagInc/node-gtfs-realtime#1]
Hello!
I was evaluating libraries for a real-time project, saw node-gtfs might be a good beginning point and then noticed the start of this project! The project would be consuming GTFS-rt data and it looks like you've got a base going here. I wanted to check before diving in if y'all would be open to PRs that further develop the tools available to folks who would use node-gtfs-realtime as a library, things like processing and query tools, Typescript bindings, etc.

Thanks so much!

**Comment by brendannee** [comment]
Absolutely - it would be great to get PRs to this library! What ideas did you have in mind?

**Comment by yoiang** [comment]
That's great to hear! I'll let you know as soon as we start diving in and seeing what we need ;)
