### ISSUE TITLE
BART example in README errors

### ISSUE THREAD

**Issue by simonprickett** [BlinkTagInc/node-gtfs-realtime#3]
Hi there - great project, I'm actually hoping to use it with BART's feed.  However, the example in the README errors like so:

```bash
% npx gtfs-realtime http://api.bart.gov/gtfsrt/tripupdate.aspx

Downloading GTFS-Realtime from http://api.bart.gov/gtfsrt/tripupdate.aspx
Error: https://api.bart.gov/gtfsrt/tripupdate.aspx: 403 Forbidden

Error: https://api.bart.gov/gtfsrt/tripupdate.aspx: 403 Forbidden
[  Error: 403 Forbidden

  - gtfs-realtime.js:18 gtfsRealtime
    [d5e1ab7c0c5fdcf3]/[gtfs-realtime]/lib/gtfs-realtime.js:18:19

  - task_queues:95 process.processTicksAndRejections
    node:internal/process/task_queues:95:5

  - gtfs-realtime.js:50 async setupImport
    [d5e1ab7c0c5fdcf3]/[gtfs-realtime]/bin/gtfs-realtime.js:50:3

] {...
```

I went here: https://www.bart.gov/schedules/developers/gtfs-realtime

And checked the feed URL from BART and got `https://api.bart.gov/gtfsrt/tripupdate.aspx` from them.  Then tried that (`https` URL rather than `http`) but same issue:

```bash
 % npx gtfs-realtime https://api.bart.gov/gtfsrt/tripupdate.aspx


Downloading GTFS-Realtime from https://api.bart.gov/gtfsrt/tripupdate.aspx
Error: https://api.bart.gov/gtfsrt/tripupdate.aspx: 403 Forbidden

Error: https://api.bart.gov/gtfsrt/tripupdate.aspx: 403 Forbidden
[  Error: 403 Forbidden
```

Is this something you've come across?  I'll dig around and see if I can figure out what's causing the 403 from BART.

**Comment by brendannee** [comment]
Maybe there was a temporary issue from BART

Try making sure you have the latest version when running from npx:

`npx gtfs-realtime@latest https://api.bart.gov/gtfsrt/tripupdate.aspx`

You can also make sure your IP has not been blocked by loading https://api.bart.gov/gtfsrt/tripupdate.aspx using curl.

**Comment by simonprickett** [comment]
Still getting 403 response with:

```
npx gtfs-realtime@latest https://api.bart.gov/gtfsrt/tripupdate.aspx
```

I get something that looks like a correct response in the browser, but only after Cloudflare jumps in to verify I am human.  This might be something BART has put in place (I'm outside the USA).

I guess we can close this as it's likely a geographical issue.

<img width="1616" alt="Screenshot 2024-02-15 at 10 38 07 PM" src="https://github.com/BlinkTagInc/node-gtfs-realtime/assets/94062/3096aae8-d55e-481f-82be-0583e35f3094">

**Comment by simonprickett** [comment]
Postman shows a 403 and the source for a Cloudflare challenge page too.

**Comment by brendannee** [comment]
Sounds like an issue with the URL itself - you are likely right that Cloudflare is flagging you because you are outside the US.

You might need to set up a proxy/vpn to make the request.

**Comment by simonprickett** [comment]
Will close, thanks - this is a shame as I used the "old" BART API for a lot of demo / teaching purposes.
