### ISSUE TITLE
Latest version does not work locally in node project

### ISSUE THREAD

**Issue by silvaDominic** [BlinkTagInc/node-gtfs-realtime#4]
Tried to use this locally in a simple node project and get complaints from Intellisense that there is no default export.

So doing something like:
```
import gtfsRealtime from 'gtfs';
```

or even

```
import * as gtfsRealtime from 'gtfs';
```

does will actually throw an error that gtfsRealtime is not a function.

This sample won't actually work anyway because the name of the package is `gtfs-realtime` not `gtfs`;

Works fine as a command using npx.

**Comment by silvaDominic** [comment]
Latest version works! Thanks!

**Comment by brendannee** [comment]
That's great to hear.

Let me know what you end up building with this library, and if it is something you'd like me to link to from the README.
