### ISSUE TITLE
? Only for BART ?

### ISSUE THREAD

**Issue by vingerha** [BlinkTagInc/node-gtfs-realtime#5]
Hi, I maintain a gtfs integration for homeassistant and in very rare cases (BART being one of them), only the aspx format is provided.
Quite a while ago I did extensive research on a solution but found none and cannot recall to have bumped into yours.
As you are still actively maintaining this, I wanted to know if this can be used generically with 'easy' enhancements.
Example: for below feeds it throws an error
http://percorsieorari.gtt.to.it/das_gtfsrt/trip_update.aspx
http://percorsieorari.gtt.to.it/das_gtfsrt/alerts.aspx
```
homeassistant_dev/aspx$ npx gtfs-realtime http://percorsieorari.gtt.to.it/das_gtfsrt/alerts.aspx
file:///usr/local/lib/node_modules/gtfs-realtime/dist/bin/gtfs-realtime.js:69
      if (error2?.code === "ENOENT") {
                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
arjan@arjan-nuc:~/docker/homeassistant_dev/aspx$ ^C
arjan@arjan-nuc:~/docker/homeassistant_dev/aspx$ npx gtfs-realtime http://percorsieorari.gtt.to.it/das_gtfsrt/trip_update.aspx
file:///usr/local/lib/node_modules/gtfs-realtime/dist/bin/gtfs-realtime.js:69
      if (error2?.code === "ENOENT") {
                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by brendannee** [comment]
What version of nodejs are you using?

It looks like it is having trouble with the optional chaining operator
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by vingerha** [comment]
Thanks for getting back
For my tests v12.22.9 but in the end I want to run this inside the HomeAssistant environment (HA-container or their own HAOS), which apparently does not have nodejs installed ... so I guess your solution would not apply

**Comment by brendannee** [comment]
I think you need nodejs 14 or higher. (Maybe version 18?)

**Comment by vingerha** [comment]
Then I will give it a pass, I just checked the feasibility to add nodejs to HA and that seems not simple ...likely impossible... as my integration is a custom one and custom integrations have their limitations. Thanks at least !
